name: "HA COPS"
version: "1.16"
slug: "ha-cops"
description: "Minimal Calibre library web interface"
url: "https://github.com/dunxd/HomeAssistantAddons/tree/main/COPS"
init: false
panel_icon: mdi:library
webui: "http://[HOST]:[PORT:8000]/index.php"
watchdog: "http://[HOST]:[PORT:8000]/index.php"
arch:
  - armv7
  - armhf
  - amd64
  - aarch64
  - i386
ports:
  8000/tcp: 8000
  873/tcp: 8873
map:
  - media:rw
options:
  title: "COPS"
  rsync: true
schema:
  title: str
  rsync: bool
  smtp_host: str?
  smtp_username: str?
  smtp_password: password?
  smtp_secure: match(^$|ssl|tls)?
  smtp_port: int?
  address_from: email?
