name: "HA COPS"
version: "1.7.3"
slug: "ha-cops"
description: "Minimal Calibre library web interface"
url: "https://github.com/dunxd/HomeAssistantAddons/tree/main/COPS"
init: false
panel_icon: mdi:library
webui: "http://[HOST]:[PORT:8000]/index.php"
watchdog: "http://[HOST]:[PORT:8000]/index.php"
arch:
  - armv7
  - armhf
  - amd64
  - aarch64
  - i386
ports:
  8000/tcp: 8000
  873/tcp: 8873
ports_description:
  8000/tcp: "HTTP port"
  873/tcp: "rsync port"
map:
  - media:rw
options:
  title: "COPS"
schema:
  title: str
