name: "COPS"
version: "0.2.13"
slug: "cops"
description: "Minimal Calibre Library Web Interface"
init: false
arch:
  - armv7
  - armhf
  - amd64
  - aarch64
  - i386
ports:
  8000/tcp: 8000
  873/tcp: 8873
map:
  - media:rw

options:
  title: "COPS"
schema:
  title: str
