name: "HA COPS"
version: "1.6"
slug: "ha-cops"
description: "Minimal Calibre library web interface"
url: "https://github.com/dunxd/HomeAssistantAddons/tree/main/COPS"
init: false
arch:
  - armv7
  - armhf
  - amd64
  - aarch64
  - i386
ports:
  8000/tcp: 8000
  873/tcp: 8873
map:
  - media:rw

options:
  title: "COPS"
schema:
  title: str
