name: "HA COPS"
version: "1.8.2.2"
slug: "ha-cops"
description: "Minimal Calibre library web interface"
url: "https://github.com/dunxd/HomeAssistantAddons/tree/main/COPS"
init: false
panel_icon: mdi:library
webui: "http://[HOST]:[PORT:8000]/index.php"
watchdog: "http://[HOST]:[PORT:8000]/index.php"
arch:
  - armv7
  - armhf
  - amd64
  - aarch64
  - i386
ports:
  8000/tcp: 8000
  873/tcp: 8873
map:
  - media:rw
options:
  title: "COPS"
  rsync: true
  smtp.host:
  smtp.username:
  smtp.password:
  smtp.secure: false
  smtp.port:
  address.from:
schema:
  title: str
  rsync: bool
  smtp.host: "str?"
  smtp.username: "str?"
  smtp.password: "password?"
  smtp.secure: bool
  smtp.port: "int?"
  address.from: "email?"
