name: "HA COPS (Kepub)"
version: "1.33a"
slug: "ha-cops-kepub"
description: "Minimal Calibre library web interface"
url: "https://github.com/dunxd/HomeAssistantAddons/tree/main/COPS"
init: false
panel_icon: mdi:library
webui: "http://[HOST]:[PORT:8000]/index.php"
watchdog: "http://[HOST]:[PORT:8000]/index.php"
arch:
  - armv7
  - armhf
  - amd64
  - aarch64
  - i386
ports:
  8000/tcp: 8000
  873/tcp: 8873
map:
  - media:rw
options:
  title: "COPS"
  library_folder: books
  rsync: true
  reader: monocle
schema:
  title: str
  library_folder: str
  rsync: bool
  reader: list(monocle|epubjs)
  smtp_host: str?
  smtp_username: str?
  smtp_password: password?
  smtp_secure: list(ssl|tls)?
  smtp_port: int?
  address_from: email?
