# /etc/rsyncd: configuration file for rsync daemon mode
uid = root
gid = root
use chroot = false

pid file = /var/run/rsyncd.pid
lock file = /var/run/rsync.lock
log file = /dev/stdout
port = 873

[books]
    path = /cops/library
    comment = eBook Library for COPS
    read only = false
    list = false