<?php

namespace SebLucas\Cops\Routing;

use SebLucas\Cops\Handlers\BaseHandler;
use SebLucas\Cops\Handlers\HandlerManager;
use SebLucas\Cops\Input\Request;
use SebLucas\Cops\Output\Format;
use RuntimeException;

/**
 * A collection of route definitions.
 */
class RouteCollection
{
    public const ROUTES_CACHE_FILE = 'url_cached_routes.php';

    /** @var array<string, array<mixed>> */
    private array $routes = [];

    /** @var array<string, string> */
    private array $staticPaths = [];

    /**
     * @param HandlerManager|null $handlerManager
     */
    public function __construct(private ?HandlerManager $handlerManager = null)
    {
        // if ($this->load()) {
        //     return;
        // }
        if (isset($handlerManager)) {
            foreach ($handlerManager->getHandlers() as $handlerClass) {
                if (method_exists($handlerClass, 'getRoutes')) {
                    $this->addRoutes($handlerClass::getRoutes(), $handlerClass);
                }
            }
            // $this->dump();
        }
    }

    /**
     * Create a RouteCollection from a pre-defined array of routes.
     * Useful for testing or caching.
     *
     * @param array<string, array<mixed>> $routes
     */
    public static function fromArray(array $routes): self
    {
        $collection = new self();
        if (!empty($routes)) {
            $collection->addRoutes($routes);
        }
        return $collection;
    }

    /**
     * Add a batch of routes.
     *
     * @param array<string, array<mixed>> $routes
     * @param class-string<BaseHandler>|null $handler
     * @throws \RuntimeException
     * @return void
     */
    public function addRoutes(array $routes, ?string $handler = null): void
    {
        foreach ($routes as $name => $route) {
            // Add params, methods and options if needed
            array_push($route, [], [], []);
            [$path, $params, $methods, $options] = $route;

            // Add static paths to the lookup table
            if (!str_contains($path, '{')) {
                $this->staticPaths[$path] = $name;
            }

            // Add ["_handler" => $handler] to params if provided
            if (isset($handler) && $handler::HANDLER !== 'html') {
                $params[Request::HANDLER_PARAM] ??= $handler;
            } else {
                // default routes can be used by html, json, phpunit, restapi without _resource, ...
            }

            // Add ["_route" => $name] to params
            $params[Request::ROUTE_PARAM] ??= $name;

            // Add default GET method
            if (empty($methods)) {
                $methods[] = 'GET';
            }

            if (isset($this->routes[$name])) {
                throw new RuntimeException('Duplicate route name ' . $name . ' for ' . $handler);
            }

            $this->routes[$name] = [$path, $params, $methods, $options];
        }
    }

    /**
     * @return array<string, array<mixed>>
     */
    public function all(): array
    {
        return $this->routes;
    }

    public function count(): int
    {
        return count($this->routes);
    }

    /**
     * Check if a static path exists.
     */
    public function hasStatic(string $path): bool
    {
        return array_key_exists($path, $this->staticPaths);
    }

    /**
     * Get route params for a static path.
     *
     * @return array<mixed>|null
     */
    public function getStatic(string $path): ?array
    {
        if (!$this->hasStatic($path)) {
            return null;
        }
        $name = $this->staticPaths[$path];
        return $this->routes[$name][1] ?? null;
    }

    public function load(): bool
    {
        $cacheFile = __DIR__ . '/' . self::ROUTES_CACHE_FILE;
        if (!file_exists($cacheFile)) {
            return false;
        }
        try {
            $cache = require $cacheFile;  // NOSONAR
            //$this->handlers = $cache["handlers"];
            $this->staticPaths = $cache["static"];
            $this->routes = $cache["routes"];
            return true;
        } catch (\Exception $e) {
            echo '<pre>' . $e . '</pre>';
            return false;
        }
    }

    public function dump(): void
    {
        $cacheFile = __DIR__ . '/' . self::ROUTES_CACHE_FILE;
        $content = '<?php' . "\n\n";
        $content .= "// This file has been auto-generated by the COPS Routing\RouteCollection class.\n\n";
        if (isset($this->handlerManager)) {
            $content .= '$handlers = ' . Format::export($this->handlerManager->getHandlers()) . ";\n\n";
        }
        $content .= '$static = ' . Format::export($this->staticPaths) . ";\n\n";
        $content .= '$routes = ' . Format::export($this->routes) . ";\n\n";
        $content .= "return [\n";
        $content .= "    'handlers' => \$handlers,\n";
        $content .= "    'static' => \$static,\n";
        $content .= "    'routes' => \$routes,\n";
        $content .= "];\n";
        file_put_contents($cacheFile, $content);
    }
}
