name: COPS-S6
version: 1.13
slug: ha-cops-s6
description: "Fork of HA-COPS using S6-Overlay"
url: "https://github.com/dunxd/HomeAssistantAddons/tree/main/COPS-S6"
panel_icon: mdi:library
webui: "http://[HOST]:[PORT:8000]/index.php"
arch:
  - aarch64
  - amd64
init: false
ports:
  8000/tcp: 8000
  873/tcp: 8873
map:
  - media:rw
options:
  title: "COPS"
  library_folder: books
  rsync: true
  reader: monocle
  koreader_sync: false
schema:
  title: str
  library_folder: str
  rsync: bool
  reader: list(monocle|epubjs)
  smtp_host: str?
  smtp_username: str?
  smtp_password: password?
  smtp_secure: list(ssl|tls)?
  smtp_port: int?
  address_from: email?
  custom_cols: str?
  koreader_sync: bool
